import {
  deleteApiKey,
  handleApiKeySave,
  loadApiKeyStatus,
  scheduleProviderSave,
  toggleApiKeyVisibility,
} from './api-keys';
import { loadGoogleAccountStatus } from './account';
import { el } from './dom';
import { showSection } from './navigation';
import {
  handlePasswordChange,
  togglePasswordField,
  togglePasswordSection,
  validateConfirmPassword,
  validateNewPassword,
} from './password';
import {
  loadWorkflowPreferences,
  scheduleModelSave,
  schedulePreferencesSave,
  updateSliderFill,
} from './preferences';
import {
  clearAllData,
  deleteAccount,
  exportData,
  restartOnboarding,
} from './privacy';
import { handleResumeUpload } from './resume';

export function attachEventListeners(): void {
  el('passwordForm')?.addEventListener('submit', (e) => {
    void handlePasswordChange(e);
  });
  el('apiKeyForm')?.addEventListener('submit', (e) => {
    void handleApiKeySave(e);
  });

  const resumeInput = el('resumeUploadInput');
  if (resumeInput) {
    resumeInput.addEventListener('change', function (this: HTMLInputElement) {
      void handleResumeUpload(this);
    });
  }

  const newPasswordInput = el('newPassword') as HTMLInputElement | null;
  const confPasswordInput = el('confirmPassword') as HTMLInputElement | null;
  if (newPasswordInput) {
    newPasswordInput.addEventListener('input', function (this: HTMLInputElement) {
      validateNewPassword(this.value);
      validateConfirmPassword();
    });
  }
  if (confPasswordInput) {
    confPasswordInput.addEventListener('input', validateConfirmPassword);
  }

  document
    .querySelector('.settings-nav, .settings-sidebar')
    ?.addEventListener('click', (e) => {
      const link = (e.target as HTMLElement).closest<HTMLElement>('a[data-section]');
      if (!link) return;
      e.preventDefault();
      showSection(link.dataset.section ?? '', e as MouseEvent);
    });

  document.addEventListener('click', (e) => {
    const target = e.target as HTMLElement;

    const fieldBtn = target.closest<HTMLElement>('.password-toggle[data-field]');
    if (fieldBtn) {
      togglePasswordField(fieldBtn.dataset.field ?? '');
      return;
    }

    const actionEl = target.closest<HTMLElement>('[data-action]');
    if (!actionEl) return;
    const action = actionEl.dataset.action;
    switch (action) {
      case 'triggerResumeUpload':
        el('resumeUploadInput')?.click();
        break;
      case 'toggleApiKeyVisibility':
        toggleApiKeyVisibility();
        break;
      case 'deleteApiKey':
        void deleteApiKey();
        break;
      case 'exportData':
        void exportData();
        break;
      case 'restartOnboarding':
        restartOnboarding();
        break;
      case 'togglePasswordSection':
        togglePasswordSection();
        break;
      case 'clearAllData':
        void clearAllData();
        break;
      case 'deleteAccount':
        void deleteAccount();
        break;
      default:
        break;
    }
  });

  const gateSlider = el('gateThresholdSlider') as HTMLInputElement | null;
  gateSlider?.addEventListener('input', function (this: HTMLInputElement) {
    const display = el('gateThresholdDisplay');
    if (display) display.textContent = `${this.value}%`;
    updateSliderFill(this);
    schedulePreferencesSave();
  });

  el('autoGenerateDocsToggle')?.addEventListener('change', schedulePreferencesSave);
  el('coverLetterToneSelect')?.addEventListener('change', schedulePreferencesSave);
  el('resumeLengthSelect')?.addEventListener('change', schedulePreferencesSave);

  const tab = new URLSearchParams(window.location.search).get('tab');
  if (tab === 'ai-setup') {
    showSection('apiKeys');
  } else if (tab === 'privacy') {
    showSection('privacy');
  }

  el('preferredModelSelect')?.addEventListener('change', scheduleModelSave);
  el('preferredProviderSelect')?.addEventListener('change', scheduleProviderSave);

  document.querySelectorAll('[role="button"][data-action]').forEach((node) => {
    node.addEventListener('keydown', (e) => {
      const ke = e as KeyboardEvent;
      if (ke.key === 'Enter' || ke.key === ' ') {
        ke.preventDefault();
        (ke.currentTarget as HTMLElement).click();
      }
    });
  });
}

export async function initSettingsPage(): Promise<void> {
  void loadApiKeyStatus();
  void loadGoogleAccountStatus();
  void loadWorkflowPreferences();
}
