import { getApiBase, getAuthToken } from '../shared/auth';
import {
  getModelSaveTimer,
  getPrefsSaveTimer,
  setModelSaveTimer,
  setPrefsSaveTimer,
} from './state-access';
import { el, inputEl, selectEl } from './dom';
import { notify } from './notify';
import type { ApplicationPreferences } from './types';

/** Human-readable labels — keep in sync with utils/llm/models.py MODEL_LABELS */
const MODEL_LABELS: Record<string, string> = {
  'gemini-3.5-flash': 'Gemini 3.5 Flash — best speed & quality (recommended)',
  'gemini-3.1-flash-lite': 'Gemini 3.1 Flash-Lite — fastest & lightest',
  'gemini-3.1-pro-preview': 'Gemini 3.1 Pro (preview) — most capable',
  'gemini-2.5-flash': 'Gemini 2.5 Flash — fast & efficient',
  'gemini-2.5-pro': 'Gemini 2.5 Pro — deep reasoning',
  'gpt-5.6-luna': 'GPT-5.6 Luna — cost-efficient high volume (recommended)',
  'gpt-5.6-terra': 'GPT-5.6 Terra — balanced intelligence & cost',
  'gpt-5.6-sol': 'GPT-5.6 Sol — flagship reasoning & coding',
  'gpt-5.5': 'GPT-5.5 — frontier professional work',
  'gpt-5.4-mini': 'GPT-5.4 mini — fast high-volume mini',
  'claude-sonnet-5': 'Claude Sonnet 5 — best speed & intelligence (recommended)',
  'claude-opus-4-8': 'Claude Opus 4.8 — complex agentic & enterprise',
  'claude-haiku-4-5': 'Claude Haiku 4.5 — fastest near-frontier',
  'claude-fable-5': 'Claude Fable 5 — highest capability agents',
  'claude-sonnet-4-6': 'Claude Sonnet 4.6 — previous Sonnet generation',
  'qwen3.6': 'Qwen 3.6 — strong local general & tools (recommended)',
  gemma4: 'Gemma 4 — newest Google open family',
  'glm-4.7-flash': 'GLM-4.7 Flash — efficient 30B-class MoE',
  'granite4.1': 'Granite 4.1 — IBM enterprise / RAG / tools',
  nemotron3: 'Nemotron 3 — NVIDIA multimodal (heavy)',
  phi4: 'Phi-4 — compact high quality (light)',
};

function showPrefsSaved(): void {
  const indicator = el('prefsSavedIndicator');
  if (!indicator) return;
  indicator.style.opacity = '1';
  window.setTimeout(() => {
    indicator.style.opacity = '0';
  }, 2000);
}

function applyPreferencesToUI(prefs: ApplicationPreferences): void {
  const slider = inputEl('gateThresholdSlider');
  const display = el('gateThresholdDisplay');
  const toggle = inputEl('autoGenerateDocsToggle');
  const toneSelect = selectEl('coverLetterToneSelect');
  const lengthSelect = selectEl('resumeLengthSelect');

  if (slider && display) {
    const pct = Math.round((prefs.workflow_gate_threshold ?? 0.5) * 100);
    slider.value = String(pct);
    display.textContent = `${pct}%`;
    updateSliderFill(slider);
  }
  if (toggle) toggle.checked = prefs.auto_generate_documents ?? false;
  if (toneSelect) toneSelect.value = prefs.cover_letter_tone ?? 'professional';
  if (lengthSelect) lengthSelect.value = prefs.resume_length ?? 'concise';
}

function readPrefsFromUI(): ApplicationPreferences {
  const slider = inputEl('gateThresholdSlider');
  const toggle = inputEl('autoGenerateDocsToggle');
  const toneSelect = selectEl('coverLetterToneSelect');
  const lengthSelect = selectEl('resumeLengthSelect');
  return {
    workflow_gate_threshold: slider ? parseFloat(slider.value) / 100 : 0.5,
    auto_generate_documents: toggle ? toggle.checked : false,
    cover_letter_tone: toneSelect ? toneSelect.value : 'professional',
    resume_length: lengthSelect ? lengthSelect.value : 'concise',
  };
}

async function persistPreferences(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${getAuthToken()}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(readPrefsFromUI()),
    });
    if (res.ok) {
      showPrefsSaved();
    } else {
      const err = (await res.json().catch(() => ({}))) as {
        message?: string;
        detail?: string;
      };
      notify(err.message || err.detail || 'Could not save preferences', 'danger');
    }
  } catch (err) {
    console.error('Error saving preferences:', err);
  }
}

export function schedulePreferencesSave(): void {
  const existing = getPrefsSaveTimer();
  if (existing) clearTimeout(existing);
  setPrefsSaveTimer(window.setTimeout(() => {
    void persistPreferences();
  }, 600));
}

export function updateSliderFill(slider: HTMLInputElement): void {
  const pct =
    ((parseInt(slider.value, 10) - parseInt(slider.min, 10)) /
      (parseInt(slider.max, 10) - parseInt(slider.min, 10))) *
    100;
  slider.style.setProperty('--val', `${pct}%`);
}

export async function loadWorkflowPreferences(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      headers: { Authorization: `Bearer ${getAuthToken()}` },
    });
    if (!res.ok) return;
    applyPreferencesToUI((await res.json()) as ApplicationPreferences);
  } catch (err) {
    console.error('Error loading workflow preferences:', err);
  }
}

export async function loadModelPreference(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      headers: { Authorization: `Bearer ${getAuthToken()}` },
    });
    if (!res.ok) return;
    const data = (await res.json()) as ApplicationPreferences;
    const sel = selectEl('preferredModelSelect');
    if (!sel || sel.options.length === 0) return;

    const saved = data.preferred_model || '';
    const hasSaved = Boolean(
      saved && Array.from(sel.options).some((opt) => opt.value === saved),
    );
    if (hasSaved) {
      sel.value = saved;
      return;
    }

    // No saved model (or stale after provider switch) → recommended = first option
    sel.selectedIndex = 0;
    if (sel.value) {
      await saveModelPreference({ quiet: true });
    }
  } catch (err) {
    console.error('Error loading model preference:', err);
  }
}

export function populateModelSelect(
  models: string[],
  selected: string | null | undefined,
): void {
  const sel = selectEl('preferredModelSelect');
  if (!sel) return;
  const current = selected ?? sel.value;
  sel.innerHTML = '<option value="">System default</option>';
  for (const model of models) {
    const opt = document.createElement('option');
    opt.value = model;
    opt.textContent = MODEL_LABELS[model] || model;
    sel.appendChild(opt);
  }
  if (current) sel.value = current;
}

export async function saveModelPreference(): Promise<void> {
  const sel = selectEl('preferredModelSelect');
  if (!sel) return;
  const current = selected ?? sel.value;
  sel.innerHTML = '';
  for (const model of models) {
    const opt = document.createElement('option');
    opt.value = model;
    opt.textContent = MODEL_LABELS[model] || model;
    sel.appendChild(opt);
  }
  if (!models.length) return;
  // Prefer saved selection when still valid; otherwise recommended (first in list)
  sel.value = current && models.includes(current) ? current : models[0]!;
}

export async function saveModelPreference(
  opts: { quiet?: boolean } = {},
): Promise<void> {
  const sel = selectEl('preferredModelSelect');
  if (!sel || !sel.value) return;
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${getAuthToken()}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        preferred_model: sel.value,
      }),
    });
    if (res.ok && !opts.quiet) {
      const indicator = el('modelSavedIndicator');
      if (indicator) {
        indicator.style.opacity = '1';
        window.setTimeout(() => {
          indicator.style.opacity = '0';
        }, 2000);
      }
    }
  } catch (err) {
    console.error('Error saving model preference:', err);
  }
}

export function scheduleModelSave(): void {
  const existing = getModelSaveTimer();
  if (existing) clearTimeout(existing);
  setModelSaveTimer(window.setTimeout(() => {
    void saveModelPreference();
  }, 600));
}
