import { getApiBase, getAuthToken } from '../shared/auth';
import {
  getModelSaveTimer,
  getPrefsSaveTimer,
  setModelSaveTimer,
  setPrefsSaveTimer,
} from './state-access';
import { el, inputEl, selectEl } from './dom';
import { notify } from './notify';
import type { ApplicationPreferences } from './types';

function showPrefsSaved(): void {
  const indicator = el('prefsSavedIndicator');
  if (!indicator) return;
  indicator.style.opacity = '1';
  window.setTimeout(() => {
    indicator.style.opacity = '0';
  }, 2000);
}

function applyPreferencesToUI(prefs: ApplicationPreferences): void {
  const slider = inputEl('gateThresholdSlider');
  const display = el('gateThresholdDisplay');
  const toggle = inputEl('autoGenerateDocsToggle');
  const toneSelect = selectEl('coverLetterToneSelect');
  const lengthSelect = selectEl('resumeLengthSelect');

  if (slider && display) {
    const pct = Math.round((prefs.workflow_gate_threshold ?? 0.5) * 100);
    slider.value = String(pct);
    display.textContent = `${pct}%`;
    updateSliderFill(slider);
  }
  if (toggle) toggle.checked = prefs.auto_generate_documents ?? false;
  if (toneSelect) toneSelect.value = prefs.cover_letter_tone ?? 'professional';
  if (lengthSelect) lengthSelect.value = prefs.resume_length ?? 'concise';
}

function readPrefsFromUI(): ApplicationPreferences {
  const slider = inputEl('gateThresholdSlider');
  const toggle = inputEl('autoGenerateDocsToggle');
  const toneSelect = selectEl('coverLetterToneSelect');
  const lengthSelect = selectEl('resumeLengthSelect');
  return {
    workflow_gate_threshold: slider ? parseFloat(slider.value) / 100 : 0.5,
    auto_generate_documents: toggle ? toggle.checked : false,
    cover_letter_tone: toneSelect ? toneSelect.value : 'professional',
    resume_length: lengthSelect ? lengthSelect.value : 'concise',
  };
}

async function persistPreferences(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${getAuthToken()}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(readPrefsFromUI()),
    });
    if (res.ok) {
      showPrefsSaved();
    } else {
      const err = (await res.json().catch(() => ({}))) as {
        message?: string;
        detail?: string;
      };
      notify(err.message || err.detail || 'Could not save preferences', 'danger');
    }
  } catch (err) {
    console.error('Error saving preferences:', err);
  }
}

export function schedulePreferencesSave(): void {
  const existing = getPrefsSaveTimer();
  if (existing) clearTimeout(existing);
  setPrefsSaveTimer(window.setTimeout(() => {
    void persistPreferences();
  }, 600));
}

export function updateSliderFill(slider: HTMLInputElement): void {
  const pct =
    ((parseInt(slider.value, 10) - parseInt(slider.min, 10)) /
      (parseInt(slider.max, 10) - parseInt(slider.min, 10))) *
    100;
  slider.style.setProperty('--val', `${pct}%`);
}

export async function loadWorkflowPreferences(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      headers: { Authorization: `Bearer ${getAuthToken()}` },
    });
    if (!res.ok) return;
    applyPreferencesToUI((await res.json()) as ApplicationPreferences);
  } catch (err) {
    console.error('Error loading workflow preferences:', err);
  }
}

export async function loadModelPreference(): Promise<void> {
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      headers: { Authorization: `Bearer ${getAuthToken()}` },
    });
    if (!res.ok) return;
    const data = (await res.json()) as ApplicationPreferences;
    const sel = selectEl('preferredModelSelect');
    if (sel && data.preferred_model) sel.value = data.preferred_model;
  } catch (err) {
    console.error('Error loading model preference:', err);
  }
}

export async function saveModelPreference(): Promise<void> {
  const sel = selectEl('preferredModelSelect');
  if (!sel) return;
  try {
    const res = await fetch(`${getApiBase()}/profile/preferences`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${getAuthToken()}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ preferred_model: sel.value }),
    });
    if (res.ok) {
      const indicator = el('modelSavedIndicator');
      if (indicator) {
        indicator.style.opacity = '1';
        window.setTimeout(() => {
          indicator.style.opacity = '0';
        }, 2000);
      }
    }
  } catch (err) {
    console.error('Error saving model preference:', err);
  }
}

export function scheduleModelSave(): void {
  const existing = getModelSaveTimer();
  if (existing) clearTimeout(existing);
  setModelSaveTimer(window.setTimeout(() => {
    void saveModelPreference();
  }, 600));
}
